# This template contains an example of running nfd-master and nfd-worker in the
# same pod.
#
apiVersion: v1
kind: Namespace
metadata:
  name: node-feature-discovery
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfd-master
  namespace: node-feature-discovery
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nfd-master
rules:
- apiGroups: ["topology.node.k8s.io"]
  resources: ["noderesourcetopologies"]
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nfd-master
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nfd-master
subjects:
- kind: ServiceAccount
  name: nfd-master
  namespace: node-feature-discovery
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nfd
  name: nfd
  namespace: node-feature-discovery
spec:
  selector:
    matchLabels:
      app: nfd
  template:
    metadata:
      labels:
        app: nfd
    spec:
      serviceAccount: nfd-master
      containers:
        - env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          image: quay.io/swsehgal/node-feature-discovery:v0.6.0-100-gbc972f6-dirty
          name: nfd-master
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
#          command:
#            - "nfd-master"
          command:
          - sleep
          args:
          - "1000000"
        - env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          image: quay.io/swsehgal/node-feature-discovery:v0.6.0-100-gbc972f6-dirty
          name: nfd-topology-update
          securityContext:
            # we need either this or to fix kubelet.sock
            # unfortunately, this also prevent to use `runAsNonRoot: true`
             runAsUser: 0
             allowPrivilegeEscalation: false
             capabilities:
               drop: ["ALL"]
             readOnlyRootFilesystem: true
#          command:
#            - "nfd-topology-updater"
#          args:
#            - "--sleep-interval=60s"
          command:
          - sleep
          args:
          - "1000000"
          volumeMounts:
            - name: kubelet-podresources-conf
              mountPath: /podresources/config.yaml
            - name: kubelet-podresources-sock
              mountPath: /podresources/kubelet.sock
            - name: host-sysfs
              mountPath: /host-sys
      volumes:
        - name: kubelet-podresources-conf
          hostPath:
            path: /var/lib/kubelet/config.yaml
        - name: kubelet-podresources-sock
          hostPath:
            path: /var/lib/kubelet/pod-resources/kubelet.sock
        - name: host-sysfs
          hostPath:
            path: /sys
